### ISSUE TITLE
wait the code!

### ISSUE THREAD

**Issue by jiaaihhy** [XuzheZ/PTNet#1]
Dear author:
Thank you for your working!
After read the paper, i want to touch the code soon!
thank you!

**Comment by XuzheZ** [comment]
Hi @jiaaihhy, thank you for your interest and sorry for the delay. The code will be updated in weeks.

Best,
Xuzhe

**Comment by XuzheZ** [comment]
Hi @jiaaihhy, thank you for your interest, the code has been released and I will add a demo and finish the README over this weekend.

Best, 
Xuzhe
