### ISSUE TITLE
Waiting for the code

### ISSUE THREAD

**Issue by JiahaoHuang99** [XuzheZ/PTNet#2]
Dear author,

Thanks for your work.
Look forward to the code.

**Comment by XuzheZ** [comment]
Hi @kaaarho , thank you for your interest and sorry for the delay. The code will be released in weeks. 

Best,
Xuzhe

**Comment by XuzheZ** [comment]
Hi @kaaarho, thank you for your interest, the code has been released. I will add a demo and finish the README over this weekend.

Best, 
Xuzhe
